title: Obada Jasem
markdown: kramdown
url: ""
baseurl: ""

# for atom feed
author:
  name: Obada Jasem
  email: obadajas0@gmail.com

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

collections_dir: all_collections
collections:
  details:
    output: true

defaults:
  - scope:
      path: "_details"
    values:
      layout: "detail"
      permalink: /details/:title/
exclude: ["sitemap.xml", "feed.xml", "LICENSE", "README.md"]
